apiVersion: v1
kind: Service
metadata:
  name: service_name # Update
spec:
  selector: 
    app: label_1 # Update
  type: LoadBalancer # ClusterIPs
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000