apiVersion: v1
kind: Service
metadata:
  name: service_name # Update
  labels:
    group: group_name # Update
spec:
  selector: 
    app: label_1 # Update
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer